# Generated by Django 3.1.2 on 2020-10-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='modified_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
