# Generated by Django 3.1.2 on 2020-10-12 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0003_auto_20201011_2135'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='photo',
            table='photos',
        ),
    ]
